CREATE TABLE IF NOT EXISTS print_job (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  schedule_id INTEGER REFERENCES schedule(id) ON DELETE CASCADE,
  task TEXT NOT NULL,
  created_at_unix INTEGER NOT NULL,
  status INTEGER NOT NULL
) STRICT;

